[package]
name = "river"
version = "0.1.0"
authors=["Jon Karrer <karrerjon@gmail.com>"]
edition="2021"
[lib]
name="utils"
path="src/lib.rs"

[[bin]]
name="bot"
path="src/main.rs"

[dependencies]
dotenv = "0.15.0"
serde = "1.0.159"
serde_json = "1.0.95"
ureq = { version = "*", features = ["json"] }
